### ISSUE TITLE
Revist windows binary installer

### ISSUE THREAD

**Issue by esc** [Blosc/bcolz#105]
The documentation still has this in it:

http://bcolz.blosc.org/install.html#installing-from-windows-binaries

Unless I am mistaken, we don't have such a thing right now?

**Comment by FrancescAlted** [comment]
No, after the excellent packages by Christopher Gohlke (and lately Anaconda), I didn't  distribute windows binaries anymore, so this can go away.

**Comment by esc** [comment]
interesting, we should provide a link to his site as a replacement for the note about the Windows installer.

**Comment by esc** [comment]
Fixed by d6d3f0bfde73f9f66ec85e7729a2d7e1969026c6
