### ISSUE TITLE
on-disk carray doesn't fail graceously

### ISSUE THREAD

**Issue by esc** [Blosc/bcolz#123]
Admittedly I am being a bit unfair by just removing the data under it's feet, but it could check if the rootdir is even there.

```
In [9]: a = bcolz.carray(np.arange(100000), rootdir='B', mode='w')

In [10]: rm -rf B

In [11]: a
Out[11]: <repr(<bcolz.carray_ext.carray at 0x7f0a2767ae60>) failed: ValueError: chunkfile B/data/__0.blp not found>
```

**Comment by esc** [comment]
I know that #152 includes checking for an existing rootdir when opening a disk-backed ctable. What I mean't was that if you move the data on disk from under the feet of the disk-backed *carray* it starts to misbehave:

```
In [15]: b
Out[15]: 
carray((100000,), float64)
  nbytes: 781.25 KB; cbytes: 286.45 KB; ratio: 2.73
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
  rootdir := 'b'
  mode    := 'w'
[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   9.99970000e+04
   9.99980000e+04   9.99990000e+04]

In [16]: b.purge()

In [17]: b
Out[17]: 
carray((100000,), float64)
  nbytes: 781.25 KB; cbytes: 286.45 KB; ratio: 2.73
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
  rootdir := 'b'
  mode    := 'w'
[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   9.99970000e+04
   9.99980000e+04   9.99990000e+04]

In [18]: b.free_cachemem 
Out[18]: <function free_cachemem>

In [19]: b.free_cachemem()

In [20]: b
Out[20]: <repr(<bcolz.carray_ext.carray at 0x7fc5328cccf8>) failed: ValueError: chunkfile b/data/__0.blp not found>
```

**Comment by CarstVaartjes** [comment]
Ah hahaha, maybe a  "you shouldn't do that" in the manual should suffice? (as you know that after opening the ctable got fully or partially altered by a different process, which to me seems malintent)

**Comment by esc** [comment]
My idea to fix this is to always access the disk-based chunks through a property and add a check for the existence of the rootdir there. I am not even sure if this is a problem in practice and it doesn't solve the problem of another process coming in while bcolz is in the middle of writing...

**Comment by esc** [comment]
Yeah, probably, but since we do offer ``purge`` now... Maybe this is a potential pothole?

**Comment by CarstVaartjes** [comment]
Ah good point about purge: the thing is that bcolz now uses the existence of rootdir to determine whether or not it is a in-mem or on-disk instance. Maybe it would be better to have a different attribute that describes whether it's in-mem, on-disk or "invalid" (to which it should switch after a purge, meaning that you should not be able to try to access it anymore). 
But that means a rather large change as there are many places where "if rootdir is not None" is used to determine the type. Still it would be nicer (and now it checks during opening if the rootdir exists, so this continuous re-checking would not be necessary). But this would be both a carray and ctable attribute, I guess?

**Comment by esc** [comment]
I fully support decoupling the type of array from the existence of a 'rootdir'. Yes, this would be a major change, but I think it would be a good one. Not sure yet on the details.

**Comment by CarstVaartjes** [comment]
Maybe make that a separate to-do issue for 0.9 or 0.10 then & we can look at it when we can pick that up for you?

**Comment by esc** [comment]
I'd keep it in the backlog for now, since we aren't even sure users will hit this and there are other items which seem more important right now. We can select it when we need to.

**Comment by esc** [comment]
But yes, a separate issue is probably a good idea.

**Comment by esc** [comment]
Made it in #158

**Comment by esc** [comment]
closing this, no longer relevant
