### ISSUE TITLE
Automatically trigger flush after append, pop, etc. for disk-based carrays

### ISSUE THREAD

**Issue by CarstVaartjes** [Blosc/bcolz#127]
Hi, 

for discussion: each disk-based carray should auto-flush after reshaping events (append, pop, delete, etc.)
Why it should be done imho: all these events already impact the actual .blps and it's just the metadata running behind.

If you ever want locking with simultaneous writes you could even argue to rewrite the metadata before the actual chunks get changed (which you could assign in a lock), but i can imagine that being a headache with the leftovers. Anyway, that's a different (long term) discussion, but for short term auto-flushing really would be a great enhancement.

And yes, I was this stupid today :) (appended 2.2bln records from 1200 different files and forget to flush at the end -> 4 hours gone oops).

**Comment by esc** [comment]
I have been thinking about this and would like to ask if a with statement would be good:

```
with bcolz.open() as ca:
    ca.append()
    ....
```

Otherwise for the flushing, do you think this behaviour would be configurable? For example with an ``autoflush`` keyword argument in the constructor?

**Comment by CarstVaartjes** [comment]
The with statement is very pythonesque, so a really good idea I think :)
Also, the autoflush keyword would be great, if you want I can make a pull request in the coming 2 weeks that implements the autoflush?

**Comment by esc** [comment]
Issue for the with statement: #135

**Comment by esc** [comment]
@CarstVaartjes feel free to implement autoflush, if you think it will be beneficial!

**Comment by CarstVaartjes** [comment]
yes, really should do it, have been swamped sorry :(

**Comment by esc** [comment]
Solved by #154 for ctables, I presume this is what you intended?

**Comment by CarstVaartjes** [comment]
Yes! #154 solves so much workarounds we had now with adding columns etc, really happy it's live :)

**Comment by esc** [comment]
cool!
