### ISSUE TITLE
ctable dtype is broken for tables with multidimensional columns

### ISSUE THREAD

**Issue by alimanfoo** [Blosc/bcolz#136]
Apologies I don't have time to submit a PR with tests right now, but I believe the dtype property on the ctable class does not correctly handle the case where a table column has more than one dimension. This causes an attempt to load data from a ctable into a numpy array via `__getitem__` to fail.

To work around this I am currently monkey-patching the ctable.dtype property with the following code:

```python
def _ctable_dtype(self):
    """The data type of this object (numpy dtype)."""
    names, cols = self.names, self.cols
    l = []
    for name in names:
        col = cols[name]
        if col.ndim == 1:
            t = (name, col.dtype)
        else:
            t = (name, (col.dtype, col.shape[1:]))
        l.append(t)
    return np.dtype(l)

bcolz.ctable.dtype = property(_ctable_dtype)
```

**Comment by FrancescAlted** [comment]
At first sight, your change looks fine to me.  I would like to see some tests on this too before using this.
