### ISSUE TITLE
addcol is broken for persistent ctables

### ISSUE THREAD

**Issue by alimanfoo** [Blosc/bcolz#137]
Calling addcol on a persistent ctable leaves the data in an inconsistent state, notebook with minimal code to reproduce is here:

http://nbviewer.ipython.org/gist/alimanfoo/6cc03872fe8054e63860/bcolz_ctable_addcol.ipynb

**Comment by CarstVaartjes** [comment]
Atm you still need to specify a rootdir (oops), for example:

    dimension_rootdir = ct.rootdir + '/' + dimension_name
    attribute_name = natural_name(attribute_id, 'a')
        ct.addcol(list(ct[attribute_name]), name=dimension_name, rootdir=dimension_rootdir, dtype=np.int64)

There's a pull request to solve this: https://github.com/Blosc/bcolz/pull/112 
But it needs to be finished (for delcol-behaviour)

**Comment by alimanfoo** [comment]
Cool, thanks, hope the PR makes it into the next release, sorry I don't
have time to help out atm. Btw I haven't looked at the PR but noticed that
with the current implementation of addcol if you pass a carray then it
won't get saved, even if you specify a rootdir in the kwargs, as carrays
are left completely untouched. IMHO a carray column should get copied into
the ctable's directory, as it does when creating a new ctable.

On Wed, Feb 25, 2015 at 11:02 PM, Carst Vaartjes <notifications@github.com>
wrote:

> Atm you still need to specify a rootdir (oops), for example:
>
> dimension_rootdir = ct.rootdir + '/' + dimension_name
> attribute_name = natural_name(attribute_id, 'a')
>     ct.addcol(list(ct[attribute_name]), name=dimension_name, rootdir=dimension_rootdir, dtype=np.int64)
>
> There's a pull request to solve this: #112
> <https://github.com/Blosc/bcolz/pull/112>
> But it needs to be finished (for delcol-behaviour)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Blosc/bcolz/issues/137#issuecomment-76080698>.
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by esc** [comment]
We merged pull requests #151 and #152 which I presume should fix this one. @alimanfoo could you give the current master a shot and let us know if you are happy with it (and close the issue if you are)?

**Comment by alimanfoo** [comment]
Thanks, will do.

On Monday, 9 March 2015, Valentin Haenel <notifications@github.com> wrote:

> We merged pull requests #151 <https://github.com/Blosc/bcolz/pull/151>
> and #152 <https://github.com/Blosc/bcolz/pull/152> which I presume should
> fix this one. @alimanfoo <https://github.com/alimanfoo> could you give
> the current master a shot and let us know if you are happy with it (and
> close the issue if you are)?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Blosc/bcolz/issues/137#issuecomment-77922577>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@gmail.com
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
Hi folks, the addcol functionality now looks good, thank you.

Probably should be raised as a separate issue, but using current master I have found a small inconsistency related to delcol behaviour after addcol: basically if you do addcol passing in an on-disk carray as the column, then call delcol to remove that column from the table, it is **not** purged from disk within the ctable's rootdir, even though keep=False is the default. Example is here:

http://nbviewer.ipython.org/gist/alimanfoo/6cc03872fe8054e63860/bcolz_ctable_delcol.ipynb

**Comment by esc** [comment]
I haven't looked at it in detail, but sounds like a bug to be fixed before 0.9.x release

V-

**Comment by CarstVaartjes** [comment]
We're getting really weird errors too (keeping the old rootdir, things that goes wrong if you fill a new column with a copy of an old column, etc)

**Comment by esc** [comment]
There is a fix for the issue raised by @alimanfoo in #170 @CarstVaartjes could you check this out perhaps and see if it fixes you issues too? If not perhaps open a new issue so that we can close this one.

**Comment by CarstVaartjes** [comment]
For me this was solved btw!

**Comment by FrancescAlted** [comment]
Closing that.  Thanks for checking @CarstVaartjes !
