### ISSUE TITLE
Slow selection with bcolz boolean array even without compression

### ISSUE THREAD

**Issue by ARF1** [Blosc/bcolz#138]
Selection with a bcolz boolean carray seems slow compared to selection with a numpy boolean array - even if compression is disabled:

```
In [20]: %%timeit
   ....: idx = bcolz.eval('carray_factor == 0', out_flavor='numpy')
   ....: df=db[idx]
   ....: 
1 loops, best of 3: 433 ms per loop

In [21]: %%timeit
   ....: idx = bcolz.eval('carray_factor == 0', cparams=bcolz.cparams(0))
   ....: df=db[idx]
   ....: 
1 loops, best of 3: 1.34 s per loop

In [23]: idx
Out[23]: 
carray((8769282,), bool)
  nbytes: 8.36 MB; cbytes: 518.17 KB; ratio: 16.53
  cparams := cparams(clevel=0, shuffle=True, cname='blosclz')
[ True  True  True ..., False False False]

In [27]: bcolz.__version__
Out[27]: '0.8.0'
```

Given the timing results in https://github.com/Blosc/bcolz/issues/78#issuecomment-59966178 I was not expecting a significant difference.

**Comment by FrancescAlted** [comment]
What sort of object is `df`?  A pandas dataframe? a bcolz object? a numpy object?  Also, you are mixing two different operations (the idx extraction and the proper indexing operation) in the same timing loop, which can fool interpretations.  Could send a self-contained example please?

**Comment by ARF1** [comment]
I am closing this as I believe it was cause by grossly mis-adjusted chunksize.

**Comment by FrancescAlted** [comment]
Do you have some hints on how the performance depends on chunksize for this use case.  Would be good if you can do some small report here.
