### ISSUE TITLE
Modification of data and appending.

### ISSUE THREAD

**Issue by MichaelWS** [Blosc/bcolz#180]
Is there any preferred way to handle modification of data in bcolz?  I have a data set in which the last 15 days or so is subject to minor modifications and the rest is static.  Should I be creating a static ctable each day and recreate the ones that could be modified?

**Comment by FrancescAlted** [comment]
I very much prefer questions be addressed to the mailing list and keep the tickets for sorting issues or enhancement proposals, so could you please use the mailing list for questions?  Thanks!
