### ISSUE TITLE
Oudated license for stdint

### ISSUE THREAD

**Issue by pombredanne** [Blosc/bcolz#188]
The license as published originally was incorrect and the upstream author fixed it:
See https://code.google.com/p/msinttypes/issues/detail?id=7&can=1

this :
https://github.com/Blosc/bcolz/blob/master/c-blosc/LICENSES/STDINT.txt

may be best replaced by this:

http://msinttypes.googlecode.com/svn/trunk/stdint.h

Cordially and thank you for bcolz!

**Comment by esc** [comment]
The license is included in bcolz via the c-blosc sources. Please file a bug agains that repository at:

https://github.com/Blosc/c-blosc

Thanks!

**Comment by FrancescAlted** [comment]
Fixed in https://github.com/Blosc/c-blosc/commit/389e086dcb1df34cc300cf4ff6905ab190fe1eae
