### ISSUE TITLE
  test failure of test test06 in test_barray.py in blz-0.6.2

### ISSUE THREAD

**Issue by idella** [Blosc/bcolz#203]
Informed by maintainer at the page listed in pypi that this is in fact the repo where blz is maintained.
 
See https://bugs.gentoo.org/show_bug.cgi?id=550714

**Comment by esc** [comment]
This is a very outdated version of `bcolz`. In fact it is so old, that it still exists under it's old name 'blz'. Suggest repackaging 'blz' to 'bcolz' and trying an up-to-date version.
