### ISSUE TITLE
Make private methods of carray/ctable actually private

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/bcolz#22]
In last 0.5 release several public methods in carray and ctable were actually meant to be private:

In [36]: c.  # a carray
c.append         c.copy           c.dtype          c.len            c.ndim           c.reshape        c.size           c.wheretrue      
c.attrs          c.cparams        c.fill_chunks    c.mkdirs         c.next           c.resize         c.sum            c.write_meta     
c.cbytes         c.create_carray  c.flush          c.mode           c.open_carray    c.rootdir        c.trim           
c.chunklen       c.dflt           c.iter           c.nbytes         c.read_meta      c.shape          c.where          

In [35]: t.   # a ctable
t.addcol         t.cbytes         t.cparams        t.dtype          t.iter           t.mode           t.ndim           t.rootdir        t.trim
t.append         t.cols           t.create_ctable  t.eval           t.len            t.names          t.open_ctable    t.shape          t.where
t.attrs          t.copy           t.delcol         t.flush          t.mkdir_rootdir  t.nbytes         t.resize         t.size

**Comment by esc** [comment]
@FrancescAlted I'd like to tackle this one next. What are you current thoughts?

**Comment by esc** [comment]
#209 has been merged, closing this one.

(some documentation upgrades are still needed..)

**Comment by FrancescElies** [comment]
If you feel I could helpful with the documentation, please let me know

**Comment by FrancescAlted** [comment]
Glad that you asked :)  Yes, documentation is very important albeit not many developers like to do it.  I suggest to produce a nice documentation addressed to developers of packages designed to use bcolz as part of the infrastructure (and I think you have quite a lot of practical skills here ;).

**Comment by FrancescElies** [comment]
I'll be glad to help with that :), I opened a new PR https://github.com/Blosc/bcolz/pull/214 for the moment only with two TODOs, if anybody has any suggestions you could write them over there

**Comment by esc** [comment]
I was thinking about iterating over the docstrings one more time, since we now have the public/private seperation in a better state., For the docstrings of the cython methods, special care is needed. IIRC you need the signature as the first line of the docstring, because Python can't introspect the signature of c-extension functions. Not sure though, I'll take a look later on today perhaps.

**Comment by esc** [comment]
I just recall not finishing the docstring overhaul the last time, because the public/private seperation wasn't done yet.

**Comment by esc** [comment]
Also overhauling the docs to use the with statement would be nice.

**Comment by esc** [comment]
Okay, but you have that already.

**Comment by FrancescElies** [comment]
Maybe you already tried, but it's worth asking, In cython we could set `embedsignature` directive to true (http://docs.cython.org/src/reference/compilation.html#compiler-directives), I searched for it but I couldn't see this being used it in the project

**Comment by esc** [comment]
Yeah, worth a shot, definitely! The more manual maintaining we can avoid the better.
