### ISSUE TITLE
Use conda instead of pip?

### ISSUE THREAD

**Issue by FrancescElies** [Blosc/bcolz#223]
as suggested in https://github.com/Blosc/bcolz/pull/218#issuecomment-121201488 would we be insterested in using conda instead of pip for travis and appveyor?

In case we don't, feel free to close this

**Comment by esc** [comment]
It's mostly the pandas dependency I guess since numpy is available as wheel(?oslt) on travis.

Feel free to be inspired by:

https://github.com/Blosc/castra/blob/master/.travis.yml

**Comment by FrancescAlted** [comment]
Yes, I think using minconda+conda is a good idea.  So +1

**Comment by FrancescElies** [comment]
Added https://github.com/Blosc/bcolz/pull/225, pending still something similar for appveyor

**Comment by FrancescElies** [comment]
PRs #225 & #226 adapt CI config files to use conda, I guess I could close this.

**Comment by esc** [comment]
thanks!
