### ISSUE TITLE
Query bug in Py 3.4

### ISSUE THREAD

**Issue by wrobstory** [Blosc/bcolz#230]
Using the diamonds dataset here: https://github.com/wrobstory/pydataseattle2015

raised this stack trace: https://gist.github.com/wrobstory/15312800b194a6da4082

Using Python 3.4.1. It raises something a little different when *not* using numexpr, but it does appear to be pretty broken on Py3.

**Comment by FrancescElies** [comment]
Hi,

to make it as easy as possible, would it be possible to get a self contained example how did you loaded `df_diamonds` into memory in the gist you posted before?

Thanks in advance

**Comment by wrobstory** [comment]
Ah, yes, of course!  I just updated the gist for the pandas import.

**Comment by FrancescAlted** [comment]
numexpr does not support Unicode strings yet, so try better:

dc["cut == b'Ideal'"]

and see if it works.

**Comment by FrancescElies** [comment]
It worked for me, @wrobstory if you could confirm that, would great.

**Comment by wrobstory** [comment]
Yes, it works! It might be useful to drop a quick line in the docs to mention this behavior. 

Thanks so much for your help!
