### ISSUE TITLE
poor compression for float32

### ISSUE THREAD

**Issue by hainm** [Blosc/bcolz#234]
Hi,

I've seen some slides showing very impressive compression ratio for dtype of integer. However, the ratio for `float32` is not that significant.

```python
In [40]: a
Out[40]:
carray((6000, 17443, 3), float32)
  nbytes: 1.17 GB; cbytes: 1.05 GB; ratio: 1.11
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
```

This is the version
```python
In [41]: b.version.__version__
Out[41]: '0.11.0.dev0'
```

I changed `clevel=9` but no help.

Did I miss anything? thanks

(i've searched float32 in issues and did google search but could not find the answer)

Hai

**Comment by FrancescElies** [comment]
Hi,

which kind of data contains `a`, from my experience, the kind of data you are trying to compress has a big impact on ratio you will achieve. on random data is difficult to achieve high compression but should work much better for time series, see below.


```python
In [1]: import bcolz

In [2]: import numpy as np

In [3]: from random import random

In [4]: N = int(1e7)

In [5]: bcolz.fromiter((random() for i in range(N)), dtype='f4,', count=N)
Out[5]: 
carray((10000000,), float32)
  nbytes: 38.15 MB; cbytes: 34.29 MB; ratio: 1.11
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[ 0.83717781  0.40694696  0.65458977 ...,  0.58797467  0.53621727
  0.30929667]

In [6]: bcolz.carray(np.linspace(0.0, 0.1, num=N), dtype='f4,')
Out[6]: 
carray((10000000,), float32)
  nbytes: 38.15 MB; cbytes: 4.08 MB; ratio: 9.35
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[  0.00000000e+00   1.00000008e-08   2.00000017e-08 ...,   9.99999791e-02
   9.99999866e-02   1.00000001e-01]
```

**Comment by buybackoff** [comment]
*Floating point* values have very different bits even for close values, so shuffle is of little help. In .NET world I am converting floats to decimals (no loss of precision) and taking diff (no loss of precision for decimals) - then shuffle shines on the diff values. Taking diff directly on floats loses precision and will be useless since the diff values are also floating point and suffer from different bits unless the diff is exactly the same (very rare cases). For real data (e.g. stock prices) I have quite high compression with decimals compared to floats, yet the speed is much slower but still faster than IO - I use Blosc for disk storage and network, not in-memory data transfer. Another point is that for certain data, e.g. financial, you have to store data as decimal even if you use it in analytical calculations as floats - to avoid issues line `0.9-0.6-0.3 <> 0.0`, so for me decimal was very good solution.

**Comment by hainm** [comment]
@FrancescElies 
my data is time series data (trajectory) from molecular dynamics simulation. It's in netcdf format.

You can have a look here: https://github.com/pytraj/pytraj/tree/master/tests/data

(files with .nc extension)

For example, with the "DPDP.nc" file, here is the info
```python
In [15]: import bcolz

In [16]: from scipy import io

In [17]: fh = io.netcdf_file("DPDP.nc")

In [18]: a = bcolz.carray(fh.variables['coordinates'].data)

In [19]: a
Out[19]:
carray((100, 332, 3), >f4)
  nbytes: 389.06 KB; cbytes: 481.07 KB; ratio: 0.81
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
```

**Comment by FrancescElies** [comment]
on that data set I saw 1 chunk of compressed data 
```python
In [22]: a.chunks
Out[22]: 
[chunk(('>f4', (332, 3)))  nbytes: 258960; cbytes: 233655; ratio: 1.11
```
Compress ratio is actually a bit better that 0.81 (65 elements are compressed, see below)

```python
In [25]: a.chunklen
Out[25]: 65

In [26]: a.len
Out[26]: 100
```
But you still have 35 elements of uncompressed data (leftovers) which makes your ratio look worse, if I understand it correctly bcolz has also some small header which can impact the compress ratio on such a small data set. So the header and the leftovers I think are making your ratio look smaller than one.

**Comment by hainm** [comment]
Yeah, it makes sense that bcolz does not have nice perf for small set. I just want to show my data example.

For the real one in my 1st post, the file is too big to upload. But i only got about 1.1 ratio.

Hai

**Comment by FrancescElies** [comment]
deeper analysis is way out of my expertise :/, maybe you could try to play with the chunklen

**Comment by hainm** [comment]
Thanks

Hai

**Comment by hainm** [comment]
Thanks for you info.

In my case, I need to be stick to netcdf format for on disk data. I looked at slides about bcolz for in memory compression and thought I could use bcolz as a in-memory backend for my program. 

Hai

**Comment by esc** [comment]
You could try to deactivate the shuffle filter, perhaps that may work better on your dataset. Also, perhaps you could odo (https://pypi.python.org/pypi/odo/0.3.2) to convert from netcdf4 to bcolz -- if you can get any compression at all, that is.

**Comment by hainm** [comment]
thanks. I will check them out.

Hai

**Comment by jzwinck** [comment]
@hainm Today you can try the "quantize" cparams option in bcolz.  If you can tolerate some loss of precision it may greatly improve your compression ratios.

**Comment by hainm** [comment]
Cool. Thanks. I will try it out.

Hai
