### ISSUE TITLE
Make bcolz.carray subclassing  simpler

### ISSUE THREAD

**Issue by mpage38** [Blosc/bcolz#238]
Currently, subclassing bcolz.carray is difficult, because in bcolz.ctable (and maybe in other classes), there exist tests like if type(...) == bcolz.carray. It means that ctable must also be subclassed with the purpose of overriding these methods and replacing those tests with: if issubclass(..., bcolz.carray).
Could these changes be done directly in bcolz library ?

**Comment by FrancescAlted** [comment]
Yes, that's a good point.  Pull requests are encouraged ;)

**Comment by mpage38** [comment]
One word to back-up my feature request: you kept the bcolz API quite simple and I think that it is a good idea ... as long as it is possible to subclass carray and ctable. If not, it is necessary to use composition to build something on top of bcolz, and this can easily become clumsy.

**Comment by FrancescAlted** [comment]
I think this should be fixed in latest releases.  If not, please reopen this ticket and add a minimal code showing the issue.
