### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by kyleabeauchamp** [Blosc/bcolz#240]
Perhaps a somewhat silly edge case, but probably nice to have this wrapped with a friendly python exception.  Observed on OSX + Anaconda + bcolz 0.10

```
import bcolz
x = bcolz.carray(zeros((0, 0), dtype='int'))
~/opt/bin/python.app: line 3: 85964 Floating point exception: 8   ~/opt/python.app/Contents/MacOS/python "$@"
```

**Comment by FrancescAlted** [comment]
Hmm, this should be happen because the carray objects are enlargeable, so a zero-size carray should be just fine.

**Comment by FrancescAlted** [comment]
After putting some thought on this, as atomic dimensions cannot be enlarged, it makes no sense to have atomic sizes with a zero dimension on them.  Will check for that and raise and error.
