### ISSUE TITLE
Context manager issue

### ISSUE THREAD

**Issue by kyleabeauchamp** [Blosc/bcolz#241]
I can't seem to use context manager style file handles to stream over a bcolz file.  E.g. the first of the following two examples raises an error after the last value is accessed.  I've also tried explicitly calling the `carray.iter()` function, with similar outcome.  

```
# xvals is just a bcolz file with arange(5) inside it.
import bcolz

with bcolz.open('./xvals', mode='r') as xvals:
    for x in xvals:
        print(x)
0
1
2
3
4

# IOError: cannot modify data because mode is 'r'

import bcolz

xvals = bcolz.open('./xvals', mode='r')
for x in xvals:
    pass
0
1
2
3
4

```

**Comment by esc** [comment]
:+1:

**Comment by kyleabeauchamp** [comment]
Thanks
