### ISSUE TITLE
Issues installing bcolz

### ISSUE THREAD

**Issue by CarstVaartjes** [Blosc/bcolz#251]
After git cloning i get:

    python setup.py build_ext --inplace
    running build_ext
    error: unknown file type '.pyx' (from '/Users/.../PyCharmProjects/bcolz/bcolz/carray_ext.pyx')

Pip installing gives:

    Collecting bcolz
      Using cached bcolz-0.11.0.tar.gz
    Requirement already up-to-date: numpy>=1.7 in /Users/carstvaartjes/anaconda/lib/python2.7/site-packages (from bcolz)
    Installing collected packages: bcolz
      Found existing installation: bcolz 0.8.0
        Uninstalling bcolz-0.8.0:
          Successfully uninstalled bcolz-0.8.0
      Running setup.py install for bcolz
        Complete output from command /Users/carstvaartjes/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-build-kSq4RU/bcolz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-dRrlZy-record/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib.macosx-10.5-x86_64-2.7
        creating build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/arrayprint.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/attrs.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/chunked_eval.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/ctable.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/defaults.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/py2help.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/toplevel.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/utils.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        copying bcolz/version.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        creating build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/all.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/common.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_attrs.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_carray.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_carray_objects.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_ctable.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_ndcarray.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/tests/test_queries.py -> build/lib.macosx-10.5-x86_64-2.7/bcolz/tests
        copying bcolz/carray_ext.pxd -> build/lib.macosx-10.5-x86_64-2.7/bcolz
        running build_ext
        error: unknown file type '.pyx' (from '/private/var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-build-kSq4RU/bcolz/bcolz/carray_ext.pyx')
    
        ----------------------------------------
      Rolling back uninstall of bcolz
    Command "/Users/.../anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-build-kSq4RU/bcolz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-dRrlZy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kj/d2jkkmlx5djbs4y48hzbc93c0000gn/T/pip-build-kSq4RU/bcolz

Is it my mac / am i doing something wrong?

**Comment by FrancescAlted** [comment]
Can you try latest setuptools?

Enviat des del meu iPhone

El 12/09/2015, a les 22:48, Carst Vaartjes <notifications@github.com> va escriure:

**Comment by CarstVaartjes** [comment]
Yes! thank you Francesc. With setuptools 18.3.1 it worked (maybe add a dependency on it?)

**Comment by FrancescAlted** [comment]
Great. I think adding the dependency is a good idea. Would you like to send a PR?

Enviat des del meu iPhone

El 13/09/2015, a les 12:51, Carst Vaartjes <notifications@github.com> va escriure:

**Comment by CarstVaartjes** [comment]
I will look into it! bquery automated testing also broke because of this :)

**Comment by brentp** [comment]
it would be nice to have a new point release of bcolz that fixes this and the mock dependency issue. we have bcolz as a dependency and we are not able to install it reliably.

**Comment by FrancescAlted** [comment]
True.  Will see if I have some time for a release during the weekend.

**Comment by CarstVaartjes** [comment]
it was solved; later problems in travis were solved by @waylonflinn by upgrading setuptools (it was a requirement but needed to be added to the travis yml explicitly)
see https://github.com/visualfabriq/bquery/pull/56

Thanks everyone!
