### ISSUE TITLE
Cannot interpolate variable with string value into eval query

### ISSUE THREAD

**Issue by BrenBarn** [Blosc/bcolz#273]
This fails:

```
>>> state = b'California'
>>> bcolz.eval('STATE==state', user_dict={'state': state, 'STATE': tmp})
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    bcolz.eval('STATE==state', user_dict={'state': state, 'STATE': tmp})
  File "c:\users\brenbarn\documents\python\extensions\bcolz\bcolz\chunked_eval.py", line 131, in eval
    raise ValueError("only numpy/carray sequences supported")
ValueError: only numpy/carray sequences supported
```

But this works:

```
>>> bcolz.numexpr.evaluate(b"STATE == state", local_dict={'state': state, 'STATE': tmp})
array([False, False, False, ..., False, False, False], dtype=bool)
```

In other words, bcolz is being too aggressive about rejecting `state` as a comparison target; numexpr can handle it just fine.

There seem to be several places in the code where bcolz uses `hasattr(obj, '__len__')` as a way of deciding whether something is a scalar or not.  This isn't a good way to do that, because a single string has a length, but should be considered a scalar.  What is needed is something like pandas `is_array_like`, which explicitly special-cases string types.

**Comment by FrancescAlted** [comment]
Yes, this is an area where things can be improved a lot.  At least I think this one is fixed :P
