### ISSUE TITLE
Cannot be installed with Numpy 1.10 due to incorrect package comparison operator

### ISSUE THREAD

**Issue by grahamc** [Blosc/bcolz#275]
Hi, installing `bcolz` with Anaconda 2.4.0 fails. Anaconda 2.4.0 ships Numpy 1.10.1. Numerically, 1.10 is less than 1.7, but version-wise it is greater. Unfortunately `bcolz` uses an invalid comparison operator: 

https://github.com/Blosc/bcolz/blob/2851981f220b8a4dbc8c63ddede8e1f6dac0380c/pavement.py#L47
In short:

```
>>> '1.9.2' > '1.7'
True
>>> '1.10' > '1.7'
False
>>> '1.10.1' > '1.7'
False
```

**Comment by grahamc** [comment]
This question / answer might be useful: https://stackoverflow.com/questions/1714027/version-number-comparison

```
>>> from distutils.version import StrictVersion
>>> StrictVersion('10.4.10') > StrictVersion('10.4.9')
True
```

**Comment by FrancescAlted** [comment]
Finally I have decided to deprecate Paver, as everything should be doable with regular setuptools.
