### ISSUE TITLE
Reading bcolz files from C

### ISSUE THREAD

**Issue by signalseeker** [Blosc/bcolz#278]
I want to read bcolz files from other languages and it would be nice if an api was provided that let you build bindings for other languages. Is there any way of doing this right now?

Thanks!

**Comment by FrancescAlted** [comment]
No, there is not provision for using the bcolz format from other languages than Python.  The suggested workaround if to convert the data to HDF5 (e.g. via `tohdf5` method) which has support for a lot of languages.
