### ISSUE TITLE
resize throws "Python int too large to convert to C long"

### ISSUE THREAD

**Issue by roman-kh** [Blosc/bcolz#288]
Calling `mycarray.resize(NEW_SIZE)` sometime throws quite a strange error:
```
  File "bcolz/carray_ext.pyx", line 1560, in bcolz.carray_ext.carray.resize (bcolz\carray_ext.c:20202)
  File "bcolz/carray_ext.pyx", line 1403, in bcolz.carray_ext.carray.append (bcolz\carray_ext.c:18995)
OverflowError: Python int too large to convert to C long
```

Consider, for example, the following code:
```
import numpy as np
import bcolz

INI_SIZE = 1e7
NEW_SIZE = 27*1e7

#n = np.arange(INI_SIZE)
n = np.ones(INI_SIZE)
#n = np.zeros(INI_SIZE)

a = bcolz.carray(n)
print repr(a)

a.resize(NEW_SIZE)
print repr(a)
```

With NEW_SIZE is 300 million the program falls with OverflowError.
However with NEW_SIZE = 270 million it finishes without errors, but something is really wrong here:
```
carray((10000000,), float64)
  nbytes: 76.29 MB; cbytes: 668.16 KB; ratio: 116.93
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[ 1.  1.  1. ...,  1.  1.  1.]
carray((-266870912,), float64)
  nbytes: -2134967296; cbytes: 1.41 MB; ratio: -1444.05
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[ 0.]
```
After resizing the array gets a negative size.

In your installation the error causing NEW_SIZE might differ, but you can easily find numbers which cause OverflowError and a negative size issue.

**Comment by FrancescAlted** [comment]
This is most probably due to the fact that you are using a 32-bit Python interpreter.  If that is the case, and you are going to need to work with very large datasets, my recommendation is to use a 64-bit one.

**Comment by FrancescAlted** [comment]
However, I detected a segfault even with 64-bit platforms.  Filed a new bug in #289 and closing this one.
