### ISSUE TITLE
Explicit column type casting

### ISSUE THREAD

**Issue by troianow** [Blosc/bcolz#293]
When happening data to a ctable, a type casting might be necessary. Consider the following example:

```python 
bc = bcolz.ctable([bcolz.carray([1,2,3]), bcolz.carray(['a', 'b', 'c'])], names=['a', 'b'] )
bc2 = bcolz.ctable([bcolz.carray([1,2,3]), bcolz.carray(['dd', 'ee', 'ff'])], names=['a', 'b'] )
bc.append(bc2)
bc
```

This outputs:
```python 
ctable((6,), [('a', '<i4'), ('b', '<U1')])
  nbytes: 48; cbytes: 32.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[(1, 'a') (2, 'b') (3, 'c') (1, 'd') (2, 'e') (3, 'f')]
```

In this case, column b of bc2 is truncated to 'U1' while one might want to change that type to 'U2'.

Would it make sense to allow recasting a particular column (or set of columns), along the lines of:
```python 
bc = bcolz.ctable([bcolz.carray([1,2,3]), bcolz.carray(['a', 'b', 'c'])], names=['a', 'b'] )
bc2 = bcolz.ctable([bcolz.carray([1,2,3]), bcolz.carray(['dd', 'ee', 'ff'])], names=['a', 'b'] )
bc.cast_col('b', 'U2') # hypothetical method
bc.append(bc2)
bc
``` 

that would lead to the output:
```python 
ctable((6,), [('a', '<i4'), ('b', '<U2')])
  nbytes: 48; cbytes: 32.00 KB; ratio: 0.00
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[(1, 'a') (2, 'b') (3, 'c') (1, 'dd') (2, 'ee') (3, 'ff')]
```

so that the append call does not truncate the appended data?

Is there a better way to approach this issue of appending data that does not fit in the existing columns of the ctable?

**Comment by FrancescAlted** [comment]
Recasting would imply expensive copies.  I think a much better method to fix this is to use the `dtype` parameter either on the carray (e.g. carray(['a'], dtype='U2') or the ctable constructor.
