### ISSUE TITLE
Weird broadcasting attempted with carrays of shape `(x, 1)`

### ISSUE THREAD

**Issue by kdmurray91** [Blosc/bcolz#295]
Hi all,

I'm puzzled by the following behavior:

**Works**:
```python
a = bcolz.ones((100, 1))
print(a.shape)
b = bcolz.zeros(a.shape)
b = bcolz.eval('a + b')
print(b.shape, b.sum())
```

**FAILS**
```python
a = bcolz.ones((int(1e8), 1))
print(a.shape)
b = bcolz.zeros(a.shape)
b = bcolz.eval('a + b')
print(b.shape, b.sum())
```

Traceback:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-752a8429c730> in <module>()
      2 print(a.shape)
      3 b = bcolz.zeros(a.shape)
----> 4 c = bcolz.eval('a + b')
      5 print(c.shape, c.sum())

/home/kevin/.virtualenvs/pymer/lib/python3.5/site-packages/bcolz/chunked_eval.py in eval(expression, vm, out_flavor, user_dict, **kwargs)
    162 
    163     return _eval_blocks(expression, vars, vlen, typesize, vm, out_flavor,
--> 164                         **kwargs)
    165 
    166 

/home/kevin/.virtualenvs/pymer/lib/python3.5/site-packages/bcolz/chunked_eval.py in _eval_blocks(expression, vars, vlen, typesize, vm, out_flavor, **kwargs)
    255         else:
    256             if scalar or dim_reduction:
--> 257                 result += res_block
    258             elif out_flavor == "carray":
    259                 result.append(res_block)

ValueError: non-broadcastable output operand with shape (1048576,) doesn't match the broadcast shape (385280,1048576)

```

I can't replicate this with arrays of shape `(x, 2)`.

Thanks in advance,

Kevin

**Comment by kdmurray91** [comment]
Could this have anything to do with #165? I am affected by that issue too.

**Comment by kdmurray91** [comment]
Oh and I nearly forgot:

```
>>> bcolz.__version__
'0.12.1'
>>> bcolz.blosc_version()
('1.4.1', '$Date:: 2014-07-08 #$')
```

**Comment by kdmurray91** [comment]
Can confirm the behavior still exists with:

```
>>> bcolz.__version__
'1.0.0rc1'
>>> bcolz.blosc_version()
('1.4.4', '$Date:: 2015-05-05 #$')
``

**Comment by FrancescAlted** [comment]
Yes, it looks like it is the same issue than #165.  Would you mind sending a PR with a fix and a test?

**Comment by kdmurray91** [comment]
@FrancescAlted more than happy to, if you can give advice on where the bug is likely to be? I'm not familiar with your code.

Cheers,
Kevin

**Comment by FrancescAlted** [comment]
Sure thing.  My guess is that there should be a problem with `carray.__getitem__()` (https://github.com/Blosc/bcolz/blob/master/bcolz/carray_ext.pyx#L1841).  I would try to debug what is going on here with tuple indexes where the second element is 1.  Luck!

**Comment by kdmurray91** [comment]
@FrancescAlted this actually appears to be related to the `_getrange()` function. It appears that the handling of the leftover chunk is inconsistent with the non-chunked version

**Comment by kdmurray91** [comment]
OK, so I think I've nailed this down, and need your feedback.

The chunked (non-leftover) part of the iteration happens in 1-d (shape (n, )) numpy arrays that get concatenated, while the leftovers are handled as a native 2d array (n, 1). I'm not so sure how to fix this.

**Comment by FrancescAlted** [comment]
Hmm, which part of the code are you talking about exactly?  Maybe it is worth moving this discussion into PR #296.  You can point out a specific line by clicking on the line number in the github code viewer and pasting the URL into the discussion panel of the PR.

**Comment by kdmurray91** [comment]
AFAICT this is fixed in #296. @FrancescAlted it would be much appreciated if you could please tag a 1.0.0rc2 release from the current master and upload to PyPI.

**Comment by FrancescAlted** [comment]
I did not forget about this.  It is just that I was trying to get out a new C-Blosc release with support for VS2008 and VS2010.  This will be very helpful for allowing bcolz (and other python libraries) to use the latest and greatest features of Blosc.  Keep tuned.

**Comment by kdmurray91** [comment]
Much appreciated, forgive the bump :smile:

**Comment by FrancescAlted** [comment]
No worries.  Please keep us informed about glitches that may have still be in RC2.
