### ISSUE TITLE
Can't import bcolz

### ISSUE THREAD

**Issue by QuantGongbin** [Blosc/bcolz#326]
I installed bcolz by pip(Python version 2.7.12),when  import bcolz, it has error like this : 

Think:~$ python -c "import bcolz"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gongbin/DEVELOP/ENTER/lib/python2.7/site-packages/bcolz/__init__.py", line 76, in <module>
    from bcolz.carray_ext import (
ImportError: /home/gongbin/DEVELOP/ENTER/lib/python2.7/site-packages/bcolz/carray_ext.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm

**Comment by leewhenyoung** [comment]
The same problem! Have you solved it?

**Comment by FrancescAlted** [comment]
Release bcolz 1.1.2 should have a fix for this.

**Comment by QuantGongbin** [comment]
@leewhenyoung I have solved this problem.The problem is that I installed Python by Anaconda, then bcolz use libstdc++.so provided by Anaconda, but this libstdc++.so lacks the nessceary symbol used in bcolz.
I solved this problem by use the nm command as follows:
nm /usr/lib/libstdc++.so.6 /usr/lib/libstdc++/so/6.0.22  
Hope it can help you

**Comment by leewhenyoung** [comment]
@QuantGongbin Bingo! thanks a lot!

**Comment by FrancescAlted** [comment]
Cool.  So it was a packaging problem.  Closing then.

**Comment by yashk2810** [comment]
When I run this command:-  nm /usr/lib/libstdc++.so.6 /usr/lib/libstdc++/so/6.0.22
I get the following error:
nm: '/usr/lib/libstdc++.so.6': No such file
nm: '/usr/lib/libstdc++/so/6.0.22': No such file

Can someone suggest another way?

**Comment by phsilveira** [comment]
@yashk2810 
I solved, with Anaconda Installed, using this command
$ `conda install libgc`

**Comment by MatthewKleinsmith** [comment]
@phsilveira 

Thank you, this worked for me. How did you know to do this?

**Comment by AbhimanyuAryan** [comment]
@phsilveira thanks it really helped 👍
