### ISSUE TITLE
how to del row for ctable?

### ISSUE THREAD

**Issue by ppd0705** [Blosc/bcolz#367]
how to del row for ctable?

**Comment by FrancescAlted** [comment]
You cannot remove a specific row, but just rows at the end (by using e.g. [trim()](http://bcolz.blosc.org/en/latest/reference.html#bcolz.carray.trim)).  If you want to delete rows in the middle, you will have to rewrite tho whole ctable.

**Comment by ppd0705** [comment]
thanks a lot , i want to delete rows in the middle.
in the end, i solved the issues with  fetchwhere() and append() to a new ctable
