### ISSUE TITLE
pip install fails in python3.6

### ISSUE THREAD

**Issue by bhaskar-manguluri** [Blosc/bcolz#378]
I have checked the installation in python2.7 and python 3.5 which works fine
but for 3.6 faced the following error
bcolz/carray_ext.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/user/work/env3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fkou0uv1/bcolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rx8lep6k/install-record.txt --single-version-externally-managed --compile --install-headers /home/tf/work/env3/include/site/python3.6/bcolz" failed with error code 1 in /tmp/pip-install-fkou0uv1/bcolz/

**Comment by FrancescAlted** [comment]
Your system is probably missing the Python 3.6 headers (python36-dev package or similar).

**Comment by bhaskar-manguluri** [comment]
yes the issue is resolved after installing python3.6 dev, you can close this.
