### ISSUE TITLE
Why do I read a ctable from disk and convert ctable to carray, the md5 value of the generated file on the disk is different each time.

### ISSUE THREAD

**Issue by ZiaWang** [Blosc/bcolz#385]
raw_ct_data = bcolz.open(rootdir=ctable_path, mode='r')
        arr = raw_ct_data[:]

        root_dir = '/path/to/new/carray'

        cparams = bcolz.cparams(cname='zstd')
        carray_data = bcolz.carray(arr, cparams=cparams, dtype=arr.dtype,
                                   rootdir=root_dir, mode='w')
        carray_data.flush()

Why do I read a ctable from disk and convert ctable to carray, the md5 value of the generated file on the disk is different each time.

I need your help

I am using the 1.1.2 version of bcolz, and I found that even in version 1.2.1, this problem still occurs.

**Comment by FrancescAlted** [comment]
This is expected.  Blosc, the underlying compressor, works in multithreading mode by default during compression, so the data blocks that are compressed faster they go into the file first, so the sequence of blocks is basically unpredictible.  You can enforce predictibility by disabling multithreading by [setting the number of threads to 1](https://bcolz.readthedocs.io/en/latest/reference.html#bcolz.set_nthreads).
