### ISSUE TITLE
current status of bcolz

### ISSUE THREAD

**Issue by kingsrd** [Blosc/bcolz#392]
thanks for making bcolz! I am considering using this for one of the projects I am working on, but apparently the last commit was about 6 months ago, is this project considered as very mature (hence not much maintenance needed) or this is no longer being actively developed? thanks

**Comment by FrancescAlted** [comment]
Well, it depends on what you understand by 'actively developed'.  The fact is that bcolz can be considered mature in many aspects, so I'd say that it is currently in maintenance mode.  Of course, doing maintenance work is not as fun as developing new features, so I am not likely continuing doing this on my free time anymore.

Having said that, the [Blosc project just entered in the NumFOCUS foundation](https://numfocus.org/blog/blosc-joins-numfocus-sponsored-projects), so you may want to sponsor the maintenance (and possible development of new features) for ensuring a brighter future to bcolz.
